# Generated by Django 5.0.4 on 2024-07-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_customuser_managers_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="saved_drugs",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="api.drug"
            ),
        ),
    ]
