# Generated by Django 5.0.4 on 2024-07-14 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_drug_customuser_saved_drugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="saved_drugs",
        ),
        migrations.DeleteModel(
            name="Drug",
        ),
    ]
