version: '3.8'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: drugs_db
      POSTGRES_USER: drugs_db_admin
      POSTGRES_PASSWORD: user
    ports:
      - "6543:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drugs_db_admin -d drugs_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      DEBUG: "True"
      DB_NAME: drugs_db
      DB_USER: drugs_db_admin
      DB_PASSWORD: user
      DB_HOST: postgres
      DB_PORT: 5432
      SECRET_KEY: "secret"
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
