# Generated by Django 5.0.4 on 2024-06-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "doid",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("treatment_count", models.IntegerField(blank=True, default=0)),
                ("edge_count", models.CharField(blank=True)),
                ("auroc", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "disease",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "dbid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("treatment_count", models.IntegerField(blank=True, default=0)),
                ("edges", models.CharField(blank=True)),
                ("auroc", models.FloatField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=1000)),
                ("group", models.CharField(blank=True, max_length=1000)),
                ("atc_code", models.CharField(blank=True, max_length=5000)),
                ("categories", models.CharField(blank=True, max_length=20000)),
                ("inchikey", models.CharField(blank=True, max_length=250)),
                ("description", models.CharField(blank=True, max_length=20000)),
                ("mechanism_large", models.CharField(blank=True, max_length=20000)),
                ("pharmacodynamics", models.CharField(blank=True, max_length=20000)),
                ("toxicity", models.CharField(blank=True, max_length=20000)),
                ("clearance", models.CharField(blank=True, max_length=20000)),
                ("half_life", models.CharField(blank=True, max_length=20000)),
                (
                    "route_of_elimination",
                    models.CharField(blank=True, max_length=20000),
                ),
                ("metabolism", models.CharField(blank=True, max_length=20000)),
                ("indication", models.CharField(blank=True, max_length=20000)),
                ("smiles", models.CharField(blank=True, max_length=1000)),
                ("pubchem_cid", models.CharField(blank=True, max_length=100)),
                (
                    "chembl_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
            ],
            options={
                "db_table": "drug",
                "ordering": ["dbid"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseIndication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(blank=True, max_length=100, null=True)),
                ("efo_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "reference_link",
                    models.CharField(blank=True, max_length=40000, null=True),
                ),
                (
                    "max_phase_for_indication",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "chembl_id",
                    models.ForeignKey(
                        db_column="chembl_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drug",
                        to_field="chembl_id",
                    ),
                ),
            ],
            options={
                "db_table": "indication",
            },
        ),
        migrations.CreateModel(
            name="DrugDiseaseProbability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction", models.FloatField(blank=True, default=0)),
                ("compound_prediction", models.FloatField(blank=True, default=0)),
                ("disease_prediction", models.FloatField(blank=True, default=0)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("trial_count", models.IntegerField(blank=True, default=0)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drugs.disease"
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drugs.drug"
                    ),
                ),
            ],
            options={
                "db_table": "drug_disease_probability",
            },
        ),
        migrations.CreateModel(
            name="MechanismOfAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mechanism_of_action",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "target_list",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("reference_list", models.TextField(blank=True, null=True)),
                (
                    "chembl_id",
                    models.ForeignKey(
                        db_column="chembl_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drug",
                        to_field="chembl_id",
                    ),
                ),
            ],
            options={
                "db_table": "mechanism_of_action",
            },
        ),
        migrations.CreateModel(
            name="MetaPathPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metapath", models.CharField(max_length=100)),
                ("percent_of_prediction", models.FloatField()),
                ("path_count", models.IntegerField()),
                ("length", models.IntegerField()),
                ("verbose", models.CharField(max_length=300)),
                (
                    "drug_disease_probability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drugdiseaseprobability",
                    ),
                ),
            ],
            options={
                "db_table": "metapath_prediction",
            },
        ),
        migrations.CreateModel(
            name="PathPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent_of_prediction", models.FloatField()),
                ("percent_of_dwpc", models.FloatField()),
                ("metapath", models.CharField(max_length=100)),
                ("length", models.IntegerField()),
                ("verbose_path", models.TextField()),
                (
                    "drug_disease_probability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drugdiseaseprobability",
                    ),
                ),
            ],
            options={
                "db_table": "path_prediction",
            },
        ),
        migrations.CreateModel(
            name="SourceEdgePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_edge", models.CharField(max_length=100)),
                ("percent_of_prediction", models.FloatField()),
                ("path_count", models.IntegerField()),
                ("distinct_metapaths", models.IntegerField()),
                (
                    "drug_disease_probability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drugdiseaseprobability",
                    ),
                ),
            ],
            options={
                "db_table": "sourceedge_prediction",
            },
        ),
        migrations.CreateModel(
            name="TargetEdgePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_edge", models.CharField(max_length=100)),
                ("percent_of_prediction", models.FloatField()),
                ("path_count", models.IntegerField()),
                ("distinct_metapaths", models.IntegerField()),
                (
                    "drug_disease_probability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drugdiseaseprobability",
                    ),
                ),
            ],
            options={
                "db_table": "targetedge_prediction",
            },
        ),
    ]
